sonar.projectKey=serviplus-s-a_api-reportes-backend
sonar.organization=serviplus-s-a
sonar.projectName=API Reportes - Backend

sonar.sources=src
sonar.tests=src,test
sonar.test.inclusions=**/*.spec.ts,**/*e2e-spec.ts

sonar.exclusions=**/node_modules/**,**/dist/**

sonar.coverage.exclusions=src/main.ts,src/**/*.module.ts,src/**/*.dto.ts,src/**/*.entity.ts,src/reportes/shared/cache/**,src/reportes/shared/auth/current-user.decorator.ts,src/reportes/shared/auth/jwt-reportes.service.ts,src/reportes/shared/utils/timeout.util.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json

sonar.qualitygate.wait=true